### ISSUE TITLE
layering.dm: conflicting redefinition of a macro

### ISSUE THREAD

**Issue by ZeWaka** [BurgerLUA/burgerstation#148]
You have `LAYER_MOB_CLOTHING_MASK` defined in two places, on line 94 and line 109
You should fix this.

I think the one on 94 is the one that should be removed, unsure though.

https://github.com/BurgerLUA/burgerstation/blob/master/code/__defines/layering.dm

**Comment by BurgerLUA** [comment]
Fixed.
