### ISSUE TITLE
what the fuck is this

### ISSUE THREAD

**Issue by ZeWaka** [BurgerLUA/burgerstation#150]
https://github.com/BurgerLUA/burgerstation/blob/831ae6087475ecdc45d531649e2a9f65eb4fcc6a/code/_core/atom/moveable/astar.dm#L1-L8

**Comment by BurgerLUA** [comment]
It was WIP code that I think I wanted to make my own a_star_pathfind like a year ago, but I forgot I made it. I'll remove it.
