### ISSUE TITLE
Turf descs

### ISSUE THREAD

**Issue by Air411** [BurgerLUA/burgerstation#242]
So, I was writing some descriptions for things, mostly walls since those are missing descriptions, and noticed that turfs all have their desc set to their full_icon_string, this overrides any desc that was set for the turf itself. 

(For example, if you set the rock wall desc to "Rock Hard", the rock walls actually generated wouldn't have that as their desc, they would have something like "/turf/simulated/wall/rock_wall_fnfs")

I know the cause of the issue, it's caused by a line in the simulated turf smoothing code that sets desc to the turf's full_icon_string. (Line 221 in _simulated.dm) I was just wondering if this was intentional or not.

(Sorry if this is the wrong place to ask this it seems like it might be a bug and I didn't know where else to put it)

**Comment by BurgerLUA** [comment]
This is a bug and it's in the correct place, don't worry. It was an old debug feature I forgot to remove.

**Comment by BurgerLUA** [comment]
Fixed
