### ISSUE TITLE
Fix Leaper Loot

### ISSUE THREAD

**Issue by BurgerLUA** [BurgerLUA/burgerstation#257]
No one likes Leaper Loot. Leaper appears to be too hard for what it gives.

**Comment by ilikesaying** [comment]
> homing bubbles that deal toxin (which noone packs meds for)
> constant teleporting that can literally be instantly after teleporting

please nerf both of these or make it less tanky because no one likes having to tank toxin while constantly running around after it fucking teleports

**Comment by BurgerLUA** [comment]
Fixed.
