### ISSUE TITLE
Quickfire/Burstfire attatchments

### ISSUE THREAD

**Issue by ChewedPencil** [BurgerLUA/burgerstation#262]
After some testing with weapon attachments, i have found that both the quickfire and burstfire adapter does not actually do what it says it does. all it does is make the gun shoot less accurately while still being jsut as fast as it was. this was all tested on the NT Carabiner, L-HON, and the DMCA

**Comment by ChewedPencil** [comment]
After Further testing, it seems that none of the automatic weapons are actually automatic anymore

**Comment by BurgerLUA** [comment]
Yeah burst fire adapter is now no longer functioning because of the new weapon system. The new weapon system also made it so that all weapons are semiautomatic at first, which caused some confusion. This was fixed.
