### ISSUE TITLE
Clear area dungeon

### ISSUE THREAD

**Issue by SylvinSeik** [BurgerLUA/burgerstation#264]
Some dungeon on the first floor has CLEAR AREA tiles around it, radio does not work in it, and light is messed up on it as well I believe? Attempting to add an image I don't know how github works so might not work
[
![image](https://user-images.githubusercontent.com/72324110/124674154-34577f00-de88-11eb-932f-ddceabf49e67.png)
](url)

**Comment by BurgerLUA** [comment]
This has been fixed.
