### ISSUE TITLE
Close menu icon randomly appearing

### ISSUE THREAD

**Issue by Moltovz** [BurgerLUA/burgerstation#273]
Title says it all, this default colored icon randomly fades in and off the screen, sometimes staying there for up to ten minutes.
![image](https://user-images.githubusercontent.com/61367602/125149430-eb612e00-e106-11eb-8eb4-7951b21f3ba0.png)

**Comment by BurgerLUA** [comment]
I don't really know why this occurs. I think I fixed it last week but I'm not sure for sure. Please let me know if it occurs next test.

**Comment by BurgerLUA** [comment]
I believe this is fixed now as I overhauled inventory a bit ago.
