### ISSUE TITLE
Automatic guns need a label for how to make them automatic

### ISSUE THREAD

**Issue by drakewill-CRL** [BurgerLUA/burgerstation#275]
Several guns that say automatic or fully automatic in their description are single-shot guns now.
Can be fixed by changing description or making them automatic.

**Comment by ilikesaying** [comment]
have you tried alt-clicking with them in hand?

**Comment by drakewill-CRL** [comment]
Doesn't work on the 556 BP SOL (Description says it has no fire rate limiters, fires 1600 per second). Remains single shot after alt-clicking.

**Comment by drakewill-CRL** [comment]
figured out the alt-click thing. It's not alt-click _on the gun_, its alt-click _empty space while holding the gun_,

**Comment by drakewill-CRL** [comment]
PR that fixes this is merged in
