### ISSUE TITLE
grinder can overflow reagent containers

### ISSUE THREAD

**Issue by AdrienTheMan** [BurgerLUA/burgerstation#285]
to reproduce it, take a grinder and a large beaker, grind stuff until you reach the cap for said beaker (120) then pour some in a glass or something then grind some more shit and you'll go over the cap, grinding after that will also remove reagent completely
havent tried with the alchemy crafting thing or whatever but im assuming it fucks up there as well

**Comment by BurgerLUA** [comment]
The cap as in the beaker's maximium amount a beaker can hold?

**Comment by AdrienTheMan** [comment]
correct, same issue with other non-beaker items that can fit in the output slot

**Comment by BurgerLUA** [comment]
Fixed.
