### ISSUE TITLE
parry does nothing

### ISSUE THREAD

**Issue by AdrienTheMan** [BurgerLUA/burgerstation#314]
parrying only makes the parry sound effect and +1 parry xp, nothing else, while it should also add the "parried" status effect on the victim

**Comment by ilikesaying** [comment]
it only stuns for like half a second or some shit, still not enough to make a good attack

**Comment by AdrienTheMan** [comment]
i dont think it even stuns its just the melee attack cooldowns, the "PARRIED!" status effect straight up doesnt appear

**Comment by BurgerLUA** [comment]
Ah, fixed it. The parried status effect would fail to be added if there was no attacker, but there was no attack assigned so it wouldn't be added.

**Comment by BurgerLUA** [comment]
Fixed.
