### ISSUE TITLE
You can empty deathbox items onto the floor by dragging.

### ISSUE THREAD

**Issue by jc-denthead** [BurgerLUA/burgerstation#425]
Reporting this for Nihisohel#7720 on the Discord.
![image](https://user-images.githubusercontent.com/63614296/131259489-923810b5-daa3-4825-8e3a-31e3cf5428bd.png)

**Comment by BurgerLUA** [comment]
Since Burgerstation has changed, I decided that there is really no real way of stopping people from opening a deathbox, and even then, I think it's fine that people can given that the only time that you would have a deathbox is on station. You shouldn't be carrying deathboxes to the mission area.
