### ISSUE TITLE
Magazines in back storage makes single bullets into stacks of bullets

### ISSUE THREAD

**Issue by Liberation546** [BurgerLUA/burgerstation#430]
Magazines inside back storage contain stacks of bullets instead of a single bullet when loading a character.

For example, if you unload an AKM magazine, you are supposed to get 30 7.62 soviet bullets (one bullet per click). Instead, every click yields you 5 bullets (the max stack size for the soviet rounds), totaling to 150 bullets per magazine if unloaded. This has no effect on shooting, or store-bought magazines. Gyro rounds are unaffected.

Compiled using VSCode, BYOND version 514.1566, on Windows 10 Pro 64-Bit, version 21H1, build 19043.1165.

**Comment by Liberation546** [comment]
Upon further testing, this does not apply in supply crates, and only happens with certain magazines (AKM and .38 included)

**Comment by Liberation546** [comment]
After more testing, this happens when you load a character.

**Comment by BurgerLUA** [comment]
Fixed, thanks for the very detailed report that quickly solved this issue.
