### ISSUE TITLE
Enemies can use grenades while asleep.

### ISSUE THREAD

**Issue by SylvinSeik** [BurgerLUA/burgerstation#441]
Title.  Very dangerous and very hilarious for fulton gamers.

**Comment by Moltovz** [comment]
Working as intended then?

**Comment by SylvinSeik** [comment]
The way it was phrased to me, they would prime the grenades while asleep, not just hold already primed grenades while asleep, I cannot entirely confirm that but someone claimed it to be the case.

**Comment by BurgerLUA** [comment]
Is this NPCs or players?

**Comment by SylvinSeik** [comment]
NPCs, someone else also reported that they could actively THROW the grenades while asleep, but just today walking into a crowd of around 6 syndicate, all of which I believe still had their grenades,none primed or threw them to my knowledge, I'll try to recreate this and close the issue if I can't.

**Comment by BurgerLUA** [comment]
Fixed this.
