### ISSUE TITLE
loading characters that aren't human makes them human but not actually

### ISSUE THREAD

**Issue by Katomou** [BurgerLUA/burgerstation#511]
the lizards with hair are back oh god oh fuck
![whydotheyhavehairwhywhywhy](https://user-images.githubusercontent.com/51431722/181378410-10082a02-96fb-4feb-a8a5-836e37a9327a.png)

**Comment by Moltovz** [comment]
That's hilarious ![unknown-1835.png](https://user-images.githubusercontent.com/61367602/181378928-9eb373d9-5ff8-432a-93d5-4b1cf34473fe.png)

**Comment by BurgerLUA** [comment]
this is cursed and a top priority

lizards with hair are the worst

**Comment by BurgerLUA** [comment]
fixed
