### ISSUE TITLE
recent commit causes issues

### ISSUE THREAD

**Issue by Liberation546** [BurgerLUA/burgerstation#543]
starting from commit f956e0d, a few things are broken on station, notably lighting, icons, and objects not stopping you sometimes.
might be an issue with subsystem loading order since wires and mapping tools are visible, even when supposed to be hidden

![image](https://user-images.githubusercontent.com/25941994/192955590-8a32b006-9366-4180-9f8e-d0a9f4d6eb0d.png)
the cryo chamber on the right has been opened

![image](https://user-images.githubusercontent.com/25941994/192958405-09a2e901-ceb9-471f-b3b7-065fec977a8b.png)
wires and smes direction visible at Mr. Scratch's building

[debug.txt](https://github.com/BurgerLUA/burgerstation/files/9671811/debug.txt)
[error.txt](https://github.com/BurgerLUA/burgerstation/files/9671812/error.txt)
[subsystem.txt](https://github.com/BurgerLUA/burgerstation/files/9671813/subsystem.txt)
related logs

**Comment by BurgerLUA** [comment]
Should be fixed now. What was happening is that the subsystems were loading in the wrong order and causing the obj initialization subsystem to crash and have this effect
