### ISSUE TITLE
supply crates dont drop anything

### ISSUE THREAD

**Issue by Liberation546** [BurgerLUA/burgerstation#544]
specifically the syndicate, nanotrasen, solarian, and slavic crates dont drop anything, the medical and magic crates are fine

**Comment by Moltovz** [comment]
![image](https://user-images.githubusercontent.com/61367602/193083934-2e18a279-d73b-483e-8d2d-25717df52177.png)

**Comment by BurgerLUA** [comment]
fixed in a previous update
