### ISSUE TITLE
Weapons staying on semi-auto regardless of firemode [quickfire adapter involved?]

### ISSUE THREAD

**Issue by Mark9013100** [BurgerLUA/burgerstation#546]
Don't have alot of info on this one, looted an MTAC off a tax collector that seemed to have a broken firemode selector

**Comment by Mark9013100** [comment]
Update: I've reason to believe mounting a quickfire adapter on the weapon caused the firemodes to break, as another player had the same issue after using a QFA.

**Comment by BurgerLUA** [comment]
I fixed this just now, thanks for reporting.
