### ISSUE TITLE
I, a Diona, consume 100u of things

### ISSUE THREAD

**Issue by ilikesaying** [BurgerLUA/burgerstation#571]
![image](https://user-images.githubusercontent.com/65475697/198192768-265ad735-dd88-48ff-bf07-6d5c0078fb31.png)
![image](https://user-images.githubusercontent.com/65475697/198192806-e805a18f-a8c9-4115-99a2-37ce4b75d236.png)

**Comment by BurgerLUA** [comment]
I think this is intentional.

**Comment by ilikesaying** [comment]
makes me fat tho
![image](https://user-images.githubusercontent.com/65475697/198948649-1ea33639-00a3-4426-830e-efa622bb4ff3.png)
