### ISSUE TITLE
combat hypnospray has no sprite

### ISSUE THREAD

**Issue by Davidththird** [BurgerLUA/burgerstation#574]
combat hypnospray has no sprite
look
![image](https://user-images.githubusercontent.com/59121922/198204150-afcd0763-3580-4cb1-a56a-c9838a4e4cae.png)
![image](https://user-images.githubusercontent.com/59121922/198204181-43093ce2-cd10-4dd4-b315-f9d1229603c0.png)

**Comment by ChewedPencil** [comment]
Same for Goliath Cloak

**Comment by Moltovz** [comment]
#579
