### ISSUE TITLE
deployable baracades block bullets from the wrong direction

### ISSUE THREAD

**Issue by Davidththird** [BurgerLUA/burgerstation#578]
![image](https://user-images.githubusercontent.com/59121922/198346500-c671a166-3d5f-4a68-ba40-9d7db6201ea0.png)
see

**Comment by Moltovz** [comment]
working as intended(?) stand on next to the barrier to shoot over it, otherwise it has a 90% ranged block chance

**Comment by Davidththird** [comment]
#582 
![image](https://user-images.githubusercontent.com/59121922/198415672-b5c41a6c-f9c9-479a-897f-a27aecc9d755.png)
