### ISSUE TITLE
Character name creation not filtered properly

### ISSUE THREAD

**Issue by V2LenKagamine** [BurgerLUA/burgerstation#589]
AKA: You can name yourself "AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH" and fill the screen upon doing anything or , "IIIIIIIIIIIIIIIIIIIIIII" - (Dont shot in github apparently, the wierd "glitched" chars.)
and that clogs admin and such

**Comment by BurgerLUA** [comment]
Fixed this in the mega update. Thanks for reporting.
