### ISSUE TITLE
[Bug] [Item Deletion] Blob spores that attach to corpses delete hand and ring slots

### ISSUE THREAD

**Issue by V2LenKagamine** [BurgerLUA/burgerstation#596]
Title.

**Comment by V2LenKagamine** [comment]
Also supposedly belt contents.

**Comment by BurgerLUA** [comment]
Oh, this is because the hand organs are being switched when you turn into a zombie so you get zombie claws. I should fix this.

**Comment by BurgerLUA** [comment]
fixed in a recent commit
