### ISSUE TITLE
[Bug] Bullets now phase through walls.

### ISSUE THREAD

**Issue by V2LenKagamine** [BurgerLUA/burgerstation#597]
https://github.com/BurgerLUA/burgerstation/commit/d5cb98a3be977f45bdffed6772de0f88e3404cc8#diff-b03fe6e14e5d57f6f051b8d885c701e7bec27bbdb088f5c798d6df6af829d55e Probably due to this change right here, but im not going through projectile code to figure it out.

**Comment by BurgerLUA** [comment]
yeah its probably that change, I'll look into it

**Comment by BurgerLUA** [comment]
fixed
