### ISSUE TITLE
how do i use this 

### ISSUE THREAD

**Issue by DavidBlanc5** [BurgerLUA/burgerstation#60]
i do not know how to use this please send help im lost and i dont know where i am please im scared call my mom

**Comment by Stalkeros2** [comment]
Ok.

**Comment by AdrienTheMan** [comment]
![drive](https://user-images.githubusercontent.com/9487319/86910054-5dc8b800-c119-11ea-9674-b7a5d1c2b877.png)
im comeing to ure house to set it uop
get ocmputer reddy
