### ISSUE TITLE
Ilikesaying's list of things that are bugged or missing

### ISSUE THREAD

**Issue by ilikesaying** [BurgerLUA/burgerstation#614]
Bugs/missing stuff (on Len's server, so may not be replicatable)
- [x] Science/Mining has no science vendors
- [x] CMO cannot be interacted with
- [x] Doors don't seem to open after round is supposed to restart
- [x] Nanotrasen officer pants/shirt don't seem to display or have armor
- [x] Janitor area machinery cannot be interacted with, light switch included
- [x] Rounds do not restart 60 seconds after rounds end
- [x] icons, runechat and damage numbers/text don't disappear after round is supposed to restart

Optional things i want
- [ ] Dumping shotgun ammo box contents into shotgun bandoliers

**Comment by ilikesaying** [comment]
![image](https://github.com/BurgerLUA/burgerstation/assets/65475697/195a8e9b-f1ce-4ef4-8721-f5891f018c49)

**Comment by ilikesaying** [comment]
![Screenshot 2023-05-19 185221](https://github.com/BurgerLUA/burgerstation/assets/65475697/39da217e-75ac-4c43-a6c4-bc62de6ce256)

**Comment by ilikesaying** [comment]
![image](https://github.com/BurgerLUA/burgerstation/assets/65475697/1bc13285-e7f6-4bd8-97a6-be4ca8eaf8be)

**Comment by BurgerLUA** [comment]
Fixed the issue with the server shitting itself after a round is supposed to restart.
