### ISSUE TITLE
Cannot make cheese

### ISSUE THREAD

**Issue by ilikesaying** [BurgerLUA/burgerstation#616]
the curdling process of making cheese never finishes, resulting in the milk and enzymes standing still in the cheese mold forever.

1. pour milk into cheese mold
2. pour enzyme into cheese mold
3. wait for the milk to finish curdling
4. it never finishes
![image](https://github.com/BurgerLUA/burgerstation/assets/65475697/6a0d27ff-4aef-4b0e-a717-5dc60c316b9f)

**Comment by BurgerLUA** [comment]
Fixed.
