### ISSUE TITLE
Map is broke for shuttles and drop pods

### ISSUE THREAD

**Issue by Infixx** [BurgerLUA/burgerstation#635]
When you click on a shuttle console or hop into a drop pod a map pops up to pick your location to launch to and its currently broke not sure if this is unofficial specific or offical too 
![0000000](https://github.com/BurgerLUA/burgerstation/assets/17614288/eb1e14e3-2f77-4faf-9b34-9a5a66af25d7)

**Comment by BurgerLUA** [comment]
uh oh

**Comment by Infixx** [comment]
> uh oh

Yeah unable to play at all except training on dummys

**Comment by Infixx** [comment]
Dumbass me accidently clicked closed but yeah its unplayble unless you want to spam train with dummys

**Comment by BurgerLUA** [comment]
this is fixed with the updated version

**Comment by Infixx** [comment]
> this is fixed with the updated version

Awesome hope unofficial is updated soon
