### ISSUE TITLE
Chemistry lacks the liquid hydrogen cell

### ISSUE THREAD

**Issue by Nezaka** [BurgerLUA/burgerstation#636]
While hosting my own server and doing chemistry, I noticed the inability to make welding fuel (And in turn, epinephrine) because there was no liquid hydrogen in the Chemistry reagent venders

**Comment by Moltovz** [comment]
Ok this is shit coding at its finest. I believe there is a hydrogen fuel cell in the chemistry vendor that you can take hydrogen from with a syringe.

**Comment by BurgerLUA** [comment]
fixed
