### ISSUE TITLE
premium ammo restocker is drawn underneath supply pod

### ISSUE THREAD

**Issue by irRegularGuy646** [BurgerLUA/burgerstation#651]
![image](https://github.com/BurgerLUA/burgerstation/assets/71989367/18695a6a-133d-4729-ae3c-1b3641908275)
![image](https://github.com/BurgerLUA/burgerstation/assets/71989367/83d803a1-2ecb-4ec8-9cc1-5713c1afdf02)

**Comment by irRegularGuy646** [comment]
this in combination with https://github.com/BurgerLUA/burgerstation/issues/650 makes premium magazine restockers unusable

**Comment by BurgerLUA** [comment]
fixed
