### ISSUE TITLE
Zachariah gave two wishgranters, that both gave rewards

### ISSUE THREAD

**Issue by muzcl** [BurgerLUA/burgerstation#656]
<img width="181" alt="image" src="https://github.com/BurgerLUA/burgerstation/assets/109846546/728fde3b-cd2a-4bbd-ac8e-3f6a8293899b">
<img width="276" alt="image" src="https://github.com/BurgerLUA/burgerstation/assets/109846546/8d273129-8901-40ad-bf78-003cb94eed78">

**Comment by BurgerLUA** [comment]
this was fixed a bit ago, thanks for reporting
