### ISSUE TITLE
Double Promotion in one day

### ISSUE THREAD

**Issue by Ryusenshu** [BurgerLUA/burgerstation#660]
Logged in and got my promotion to job level 2 in sec
Due to an issue i had (a boss dying but the boss music keep repeating forever) , i went sleeper, logged out and reconnected
After i loaded my char back in i got promoted to level 3

![Screenshot_1](https://github.com/BurgerLUA/burgerstation/assets/95751821/21d59566-ec89-4c69-b5ca-4fadc60169ff)
![Screenshot_2](https://github.com/BurgerLUA/burgerstation/assets/95751821/1138d953-2fbd-48a7-acef-09e9058ebfe9)

**Comment by Ryusenshu** [comment]
![Screenshot_1](https://github.com/BurgerLUA/burgerstation/assets/95751821/21d59566-ec89-4c69-b5ca-4fadc60169ff)
![Screenshot_2](https://github.com/BurgerLUA/burgerstation/assets/95751821/1138d953-2fbd-48a7-acef-09e9058ebfe9)

**Comment by BurgerLUA** [comment]
this was fixed a bit ago, thanks for reporting
