### ISSUE TITLE
Unable to edit new characters

### ISSUE THREAD

**Issue by Burning02** [BurgerLUA/burgerstation#664]
When attempting to create a new character, I am unable to edit them past their name and race. I am unsure if this is only a issue on my side, as when I last asked someone if they had the same issues ingame when creating new characters, they didn't give a definitive answer.

**Comment by Sasha2214** [comment]
Also, if you need to change anything besides race, go into bathrooms, bottom right of hypersleep beds, go infront of the mirror and fix yourself up
